#!/usr/bin/env bash
set -euo pipefail

# Generates a Release file for apt/dists/<suite> via apt-ftparchive.
#
# Field values (Origin/Label/Suite/Codename all equal to the suite name,
# Origin/Label prefixed "apt ") are matched exactly against the live
# repo's currently-served Release file (confirmed via the still-working
# trixie-dev suite, which also revealed the existing pipeline is aptly-
# generated) -- this avoids apt's "repository changed its Origin/Label
# value" warning on existing users' first update after cutover.
#
# Usage: generate-release.sh <suite> <arch...>

if [[ $# -lt 2 ]]; then
    echo "usage: $0 <suite> <arch...>" >&2
    exit 1
fi

SUITE="$1"
shift
ARCHES=("$@")

DISTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../apt/dists/${SUITE}" && pwd)"

apt-ftparchive \
    -o "APT::FTPArchive::Release::Origin=apt ${SUITE}" \
    -o "APT::FTPArchive::Release::Label=apt ${SUITE}" \
    -o "APT::FTPArchive::Release::Suite=${SUITE}" \
    -o "APT::FTPArchive::Release::Codename=${SUITE}" \
    -o "APT::FTPArchive::Release::Architectures=${ARCHES[*]}" \
    -o "APT::FTPArchive::Release::Components=main" \
    -o "APT::FTPArchive::Release::Description=Generated by aptly" \
    release "${DISTS_DIR}"
